### ISSUE TITLE
Performance with many notebooks

### ISSUE THREAD

**Issue by bashimao** [anibali/showoff#2]
Once you have a couple of notebooks the rendering performance on the main-screen decreases significantly. It would be good if we could have something like a list of "folders" or "categories" on the left.

In my imagination, there should be a small edit-box right-aligned in the notebook list that becomes visible, once you click the edit button. There you then enter the "category"-name (for instance "cat detector"). Once you leave edit-mode, the site refreshes, and in the left list should appear something like "cat detector (1)". If you set this category-label for another notebook it should change to "cat detector (2)" and so on. If the label is clicked, the notebook-list title should change to "cat detector Notebooks" and the notebook-list should be restricted to the "cat detector"-experiments.

Newly created notebooks and old notebooks that were created before the introduction of category-labels should end up in a dummy-category called "Uncategorized".

**Comment by anibali** [comment]
Just to clarify, you are saying that the notebook index page is "laggy" after it finishes loading? This is unusual as the DOM should be staying the same. If this isn't a browser-specific issue then it should probably be addressed directly.

**Comment by anibali** [comment]
Created a separate issue for the cause of the performance problems: https://github.com/anibali/showoff/issues/3

**Comment by bashimao** [comment]
Thanks!

**Comment by anibali** [comment]
I've implemented a tagging system which achieves a similar goal to categories.
